name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
    pipeline: 
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [17.x]
      steps:
        - uses: actions/checkout@v2
        - name: Staring node.js ${{matrix.node-version}}
          uses: actions/setup-node@v1
            with: 
              node-version: ${{matrix.node-version}}
        - name: install modules
          run: npm install
        - name: build production project
          run: npm run build:prod
        - name: linting typescript
          run: npm run lint:ts
        - name: linting styles
          run: npm run stylelint
        - name: run unit tests
          run: npm run test:unit
      

