name: CI
run-name: CI
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - run: npm ci --force
            - run: npm run build:prod
            - run: npm run lint:ts
            - run: npm run stylelint
            - run: npm run test:unit
            - run: npm run build-storybook
            - run: npm run test:ui:ci
